version: '2.1'

services:
  spotifyradio:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - dev
    volumes:
      - .:/spotify-radio
      - node_modules:/spotiry-radio/node_modules
    ports:
      - 3000:3000

  test:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - test
    volumes:
      - .:/spotify-radio
      - node_modules:/spotiry-radio/node_modules

  test-watch:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - test:watch
    volumes:
      - .:/spotify-radio
      - node_modules:/spotiry-radio/node_modules

  test-coverage:
    image: spotify-radio
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - test:coverage
    volumes:
      - .:/spotify-radio
      - node_modules:/spotiry-radio/node_modules

volumes:
  node_modules: {}